# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NetworkDesignToolsDialog
                                 A QGIS plugin
 Network Design Tools
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-24
        git sha              : $Format:%H$
        copyright            : (C) 2021 by ESDM
        email                : paulm@esdm.co.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
ui_PropertyCountDialog, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'property_count_dialog_base.ui'))


class PropertyCountDialog(QtWidgets.QDialog, ui_PropertyCountDialog):
    def __init__(self, numproperies, parent=None):
        """Constructor."""
        super(PropertyCountDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect

        
        self.setupUi(self)

        self.lblPropertyCount.setText(str(numproperies) + ' properties selected')

       # self.lblPropertyCount = str(numproperies) + ' properties selected, updated from dialog'